version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0

    working_directory: ~/rental-car-server

    environment:
      # Variabel lingkungan untuk koneksi ke PostgreSQL
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/rental_car_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

    steps:
      - checkout  # Mengambil kode dari repositori

      # Menjalankan container PostgreSQL
      - run:
          name: Start PostgreSQL
          command: |
            docker run -d --name postgres -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -p 5432:5432 postgres:latest

      # Menunggu PostgreSQL untuk siap
      - run:
          name: Wait for PostgreSQL to be ready
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      # Menjalankan migrasi database menggunakan Flyway
      - run:
          name: Run Flyway Migration
          command: ./mvnw flyway:migrate

      # Menjalankan unit test
      - run:
          name: Run Unit Tests
          command: ./mvnw test

      # Build aplikasi Spring Boot
      - run:
          name: Build Project
          command: ./mvnw clean package

workflows:
  build-and-test:
    jobs:
      - build-and-test